**Lab4 PART-2**

**Linear regression using PyTorch built-ins**

**Dataset and DataLoader**

In [10]:
import numpy as np
import torch

In [2]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [3]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [4]:
from torch.utils.data import TensorDataset, DataLoader

In [5]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [9]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [8]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [ 73.,  67.,  43.]])
tensor([[ 81., 101.],
        [ 22.,  37.],
        [103., 119.],
        [119., 133.],
        [ 56.,  70.]])


**nn.Linear**

In [11]:
import torch.nn as nn

In [12]:
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.4448,  0.2695, -0.5202],
        [-0.4764,  0.1753,  0.1780]], requires_grad=True)
Parameter containing:
tensor([-0.5260, -0.1905], requires_grad=True)


**Optimizer**

In [24]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.4448,  0.2695, -0.5202],
         [-0.4764,  0.1753,  0.1780]], requires_grad=True),
 Parameter containing:
 tensor([-0.5260, -0.1905], requires_grad=True)]

In [16]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

**Loss Function**

In [17]:
import torch.nn.functional as F

In [18]:
loss_fn = F.mse_loss

In [23]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(7737.6299, grad_fn=<MseLossBackward0>)


**Train the model**

In [27]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()          
            opt.zero_grad()
        
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [26]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 644.2938
Epoch [20/100], Loss: 394.4937
Epoch [30/100], Loss: 350.0249
Epoch [40/100], Loss: 314.1439
Epoch [50/100], Loss: 282.5009
Epoch [60/100], Loss: 254.5285
Epoch [70/100], Loss: 229.7889
Epoch [80/100], Loss: 207.8987
Epoch [90/100], Loss: 188.5194
Epoch [100/100], Loss: 171.3534


In [28]:
prediction = model(inputs)
prediction

tensor([[ 62.4827,  71.9512],
        [ 79.1389,  99.2235],
        [117.1202, 133.6080],
        [ 51.8282,  46.4823],
        [ 78.5368, 111.0601]], grad_fn=<AddmmBackward0>)

In [29]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [30]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[59.4890, 69.0828]], grad_fn=<AddmmBackward0>)