**Lab4 PART-1**

**Linear regression model from scratch**

In [10]:
import numpy as np
import torch

In [11]:
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')

In [12]:
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
weight = torch.randn(2, 3, requires_grad=True)
bias = torch.randn(2, requires_grad=True)
print(weight,"\n",bias)

tensor([[ 1.1902,  0.3437,  1.2908],
        [-0.3581, -0.2177, -0.4975]], requires_grad=True) 
 tensor([0.6575, 0.0388], requires_grad=True)


In [ ]:
def model(inputs):
    return inputs @ weight.t() + bias
print(inputs)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])


In [ ]:
prediction = model(inputs)
print(prediction)

tensor([[166.0735, -62.0825],
        [221.8212, -83.5481],
        [225.1249, -89.1447],
        [184.5967, -64.2576],
        [206.1307, -80.3966]], grad_fn=<AddBackward0>)


In [ ]:
print(targets)

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


**Loss function**

In [ ]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [ ]:
loss = mse(prediction, targets)
print(loss)

tensor(20570.1348, grad_fn=<DivBackward0>)


**Compute gradients**

In [ ]:
loss.backward(retain_graph=True)
print(weight.grad)
print(bias.grad)

tensor([[ 365.4922, -335.0515,   -8.4536],
        [ 218.7892, -157.1840,  -75.3473]])
tensor([2.8388, 1.2357])


**Train the model using gradient descent**

In [ ]:
with torch.no_grad():
    weight -= weight.grad * 1e-5
    bias -= bias.grad * 1e-5
    weight.grad.zero_()
    bias.grad.zero_()

In [ ]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(14157.3857, grad_fn=<DivBackward0>)


**Train for multiple epochs**

In [ ]:
for i in range(100):
    prediction = model(inputs)
    loss = mse(prediction, targets)
    loss.backward()
    with torch.no_grad():
        weight -= weight.grad * 1e-5
        bias -= bias.grad * 1e-5
        weight.grad.zero_()
        bias.grad.zero_()

In [ ]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(278.1065, grad_fn=<DivBackward0>)


In [ ]:
prediction

tensor([[ 63.1426,  61.0919],
        [ 89.2896,  80.4604],
        [ 92.9771, 116.3524],
        [ 55.5012,  43.4174],
        [ 94.2835,  85.8566]], grad_fn=<AddBackward0>)

In [14]:
targets

array([[ 56.],
       [ 81.],
       [119.],
       [ 22.],
       [103.]], dtype=float32)