In [23]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score

In [4]:
stopwords = ["a", "about", "above", "after", "again", "against", "all", "am",
"an", "and", "any", "are", "as", "at", "be", "because", "been", "before",
"being", "below", "between", "both", "but", "by", "could", "did", "do",
"does", "doing", "down", "during", "each", "few", "for", "from", "further",
"had", "has", "have", "having", "he", "he'd", "he'll", "he's", "her", "here",
"here's", "hers", "herself", "him", "himself", "his", "how", "how's", "i",
"i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "it", "it's", "its",
"itself", "let's", "me", "more", "most", "my", "myself", "nor", "of", "on",
"once", "only", "or", "other", "ought", "our", "ours", "ourselves", "out",
"over", "own", "same", "she", "she'd", "she'll", "she's", "should", "so",
"some", "such", "than", "that", "that's", "the", "their", "theirs", "them",
"themselves", "then", "there", "there's", "these", "they", "they'd",
"they'll", "they're", "they've", "this", "those", "through", "to", "too",
"under", "until", "up", "very", "was", "we", "we'd", "we'll", "we're",
"we've", "were", "what", "what's", "when", "when's", "where", "where's",
"which", "while", "who", "who's", "whom", "why", "why's", "with", "would",
"you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself",
"yourselves"]

In [5]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [19]:
datasets = pd.read_csv('/content/drive/MyDrive/Data/SPAM1.csv') 
datasets["v1"]=np.where(datasets["v1"]=='spam',1,0)
print("\nData :\n",datasets.head(20))


Data :
     v1                                                 v2
0    1  Free entry in 2 a wkly comp to win FA Cup fina...
1    1  FreeMsg Hey there darling it's been 3 week's n...
2    1  WINNER!! As a valued network customer you have...
3    1  Had your mobile 11 months or more? U R entitle...
4    1  SIX chances to win CASH! From 100 to 20,000 po...
5    1  URGENT! You have won a 1 week FREE membership ...
6    1  XXXMobileMovieClub: To use your credit, click ...
7    1  England v Macedonia - dont miss the goals/team...
8    1  Thanks for your subscription to Ringtone UK yo...
9    1  07732584351 - Rodger Burns - MSG = We tried to...
10   1  SMS. ac Sptv: The New Jersey Devils and the De...
11   1  Congrats! 1 year special cinema pass for 2 is ...
12   1  As a valued customer, I am pleased to advise y...
13   1  Urgent UR awarded a complimentary trip to Euro...
14   1  Did you hear about the new \Divorce Barbie\"? ...
15   1  Please call our customer service representativ...
16   

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(datasets["v2"], datasets["v1"],random_state=72)
X_test.shape

(129,)

**CountVectorizer**

**Perform Count Vectorization on training data**

In [15]:
vectorizer = CountVectorizer(ngram_range = (1, 1),stop_words=stopwords)
vectorizer.fit(X_train)
X_train_vectorized = vectorizer.fit_transform(X_train)
print(X_train_vectorized.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


/usr/local/lib/python3.7/dist-packages/sklearn/feature_extraction/text.py:401: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['let', 'll', 're', 've'] not in stop_words.
  % sorted(inconsistent)


**Apply the Naive Bayes on Vectorized data.**

In [25]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()
nb.fit(X_train_vectorized,y_train)

MultinomialNB()

In [26]:
predictions = nb.predict(vectorizer.transform(X_test))
print("Accuracy: ", accuracy_score(y_test, predictions))
print("Precision: ", precision_score(y_test, predictions))
print("Recall: ", recall_score(y_test, predictions))

Accuracy:  0.9689922480620154
Precision:  0.9555555555555556
Recall:  0.9555555555555556


**Apply the Decision Tree Classifier on Vectorized data.**

In [27]:
from sklearn.tree import DecisionTreeClassifier
dtcf = DecisionTreeClassifier()
dtcf.fit(X_train_vectorized, y_train)

DecisionTreeClassifier()

In [42]:
predictions = dtcf.predict(vectorizer.transform(X_test))
print("Accuracy: ", accuracy_score(y_test, predictions))
print("Precision: ", precision_score(y_test, predictions))
print("Recall: ", recall_score(y_test, predictions))

Accuracy:  0.8992248062015504
Precision:  0.9210526315789473
Recall:  0.7777777777777778


**TFIDF Vectorizer**

**Perform IFIDF Vectorization on training data.**

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(ngram_range = (1, 1),stop_words = stopwords)
vectorizer.fit(X_train)
X_train_tfidf_vectorized = vectorizer.transform(X_train)
print(X_train_tfidf_vectorized.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


/usr/local/lib/python3.7/dist-packages/sklearn/feature_extraction/text.py:401: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['let', 'll', 're', 've'] not in stop_words.
  % sorted(inconsistent)


**Apply the Naive Bayes on IFIDF Vectorized data.**

In [31]:
nb = MultinomialNB()
nb.fit(X_train_tfidf_vectorized, y_train)

MultinomialNB()

In [37]:
predictions = nb.predict(vectorizer.transform(X_test))
print("Accuracy: ", accuracy_score(y_test, predictions))
print("Precision: ", precision_score(y_test, predictions))
print("Recall: ", recall_score(y_test, predictions))

Accuracy:  0.9224806201550387
Precision:  1.0
Recall:  0.7777777777777778


**Apply the Decision Tree Classifier on IFIDF Vectorized data.**

In [38]:
dtcf = DecisionTreeClassifier()
dtcf.fit(X_train_tfidf_vectorized, y_train)

DecisionTreeClassifier()

In [41]:
predictions = dtcf.predict(vectorizer.transform(X_test))

print("Accuracy: ", accuracy_score(y_test, predictions))
print("Precision: ", precision_score(y_test, predictions))
print("Recall: ", recall_score(y_test, predictions))

Accuracy:  0.8992248062015504
Precision:  0.9210526315789473
Recall:  0.7777777777777778
